POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
  "email": "issuer@example.com",
  "password": "securePassword123",
  "role": "issuer",
  "companyName": "AuditCorp",
  "licence": "AUD-987654321",
  "organization": "Nexus"
}
###
POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
  "email": "auditor@example.com",
  "password": "securePassword123"
}
###
POST http://localhost:3000/download
Content-Type: application/json

{
  "uuid": "49e064cf-481d-47d3-b93c-b7486c574e22",
  "keys": ["855126"],
  "rows": ["B92478296"]
}

###
GET http://localhost:3000/demand/getDemand
Content-Type: application/json

{

}